server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.lyx.taotao.xml        # mybatis配置文件所在路径
  type-aliases-package: boot.entities   # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/lyx.taotao.mapper/lyx.taotao.mapper.lyx.taotao.xml                       # mapper映射文件

spring:
   application:
    name: Provider
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/c       #    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包#    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200    # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
       defaultZone: http://localhost7001:7001/eureka,http://localhost7002:7002/eureka,http://localhost7003:7003/eureka
  instance:
    instance-id: provider8003
    prefer-ip-address: true




